<?php

namespace Proxies\__CG__\RiskBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Player extends \RiskBundle\Entity\Player implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'RiskBundle\\Entity\\Player' . "\0" . 'id', '' . "\0" . 'RiskBundle\\Entity\\Player' . "\0" . 'name', '' . "\0" . 'RiskBundle\\Entity\\Player' . "\0" . 'color', '' . "\0" . 'RiskBundle\\Entity\\Player' . "\0" . 'symbol', '' . "\0" . 'RiskBundle\\Entity\\Player' . "\0" . 'nbboxes', '' . "\0" . 'RiskBundle\\Entity\\Player' . "\0" . 'nbsoldiers', '' . "\0" . 'RiskBundle\\Entity\\Player' . "\0" . 'game', '' . "\0" . 'RiskBundle\\Entity\\Player' . "\0" . 'boxes'];
        }

        return ['__isInitialized__', '' . "\0" . 'RiskBundle\\Entity\\Player' . "\0" . 'id', '' . "\0" . 'RiskBundle\\Entity\\Player' . "\0" . 'name', '' . "\0" . 'RiskBundle\\Entity\\Player' . "\0" . 'color', '' . "\0" . 'RiskBundle\\Entity\\Player' . "\0" . 'symbol', '' . "\0" . 'RiskBundle\\Entity\\Player' . "\0" . 'nbboxes', '' . "\0" . 'RiskBundle\\Entity\\Player' . "\0" . 'nbsoldiers', '' . "\0" . 'RiskBundle\\Entity\\Player' . "\0" . 'game', '' . "\0" . 'RiskBundle\\Entity\\Player' . "\0" . 'boxes'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Player $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setColor($color)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setColor', [$color]);

        return parent::setColor($color);
    }

    /**
     * {@inheritDoc}
     */
    public function getColor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getColor', []);

        return parent::getColor();
    }

    /**
     * {@inheritDoc}
     */
    public function setSymbol($symbol)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSymbol', [$symbol]);

        return parent::setSymbol($symbol);
    }

    /**
     * {@inheritDoc}
     */
    public function getSymbol()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSymbol', []);

        return parent::getSymbol();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbboxes($nbboxes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbboxes', [$nbboxes]);

        return parent::setNbboxes($nbboxes);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbboxes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbboxes', []);

        return parent::getNbboxes();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbsoldiers($nbsoldiers)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbsoldiers', [$nbsoldiers]);

        return parent::setNbsoldiers($nbsoldiers);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbsoldiers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbsoldiers', []);

        return parent::getNbsoldiers();
    }

    /**
     * {@inheritDoc}
     */
    public function setGame(\RiskBundle\Entity\Game $game = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGame', [$game]);

        return parent::setGame($game);
    }

    /**
     * {@inheritDoc}
     */
    public function getGame()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGame', []);

        return parent::getGame();
    }

    /**
     * {@inheritDoc}
     */
    public function addBox(\RiskBundle\Entity\Box $box)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBox', [$box]);

        return parent::addBox($box);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBox(\RiskBundle\Entity\Box $box)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBox', [$box]);

        return parent::removeBox($box);
    }

    /**
     * {@inheritDoc}
     */
    public function getBoxes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBoxes', []);

        return parent::getBoxes();
    }

    /**
     * {@inheritDoc}
     */
    public function sortById($a, $b)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'sortById', [$a, $b]);

        return parent::sortById($a, $b);
    }

}
