<?php

namespace RiskBundle\Repository;

/**
 * BoxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoxRepository extends \Doctrine\ORM\EntityRepository {

    public function videBox($idBox) {

        $videBox = $this->getEntityManager()->createQueryBuilder();
        $videBox->update('RiskBundle:Slot', 's')
                ->set('s.free', 'true')
                ->where('s.box=:idb')
                ->setParameter('idb', $idBox);

        $q = $videBox->getQuery();
        $q->execute();

        $resteUn = $this->getEntityManager()->createQueryBuilder();
        $resteUn->update('RiskBundle:Slot', 's')
                ->set('s.free', 'false')
                ->where('s.box=:idb')
                ->andWhere('s.position=1')
                ->setParameter('idb', $idBox);

        $q = $resteUn->getQuery();
        $q->execute();
    }

    public function defineSlotBox($idBox, $nbSoldiers) {

        $qb = $this->getEntityManager()->createQueryBuilder();

        for ($position = 1; $position < 10; $position++) {
            if ($position <= $nbSoldiers) {
                $qb->update('RiskBundle:Slot', 's')
                        ->set('s.free', 'false')
                        ->where('s.box=:idb')
                        ->andWhere('s.position=' . $position)
                        ->setParameter('idb', $idBox);

                $q = $qb->getQuery();
                $q->execute();
            } else {
                $qb->update('RiskBundle:Slot', 's')
                        ->set('s.free', 'true')
                        ->where('s.box=:idb')
                        ->andWhere('s.position=' . $position)
                        ->setParameter('idb', $idBox);

                $q = $qb->getQuery();
                $q->execute();
            }
        }
    }

}
