<?php

namespace RiskBundle\Repository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends \Doctrine\ORM\EntityRepository {

    public function getBoxes($idGame) {
        return $this->getEntityManager()
                        ->createQuery(
                                'select b '
                                . 'from RiskBundle:Box b '
                                . 'inner join RiskBundle:Player p with b.player=p.id '
                                . 'inner join RiskBundle:Game g with p.game=g.id '
                                . 'where g.id = :idg '
                                . 'order by b.id ASC'
                        )
                        ->setParameter('idg', $idGame)
                        ->getResult();
    }

}
