<?php

namespace RiskBundle\Repository;

/**
 * BoxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends \Doctrine\ORM\EntityRepository {

    public function countSoldiers($idPlayer) {
        return $this->getEntityManager()
                        ->createQuery(
                                'select count(s) '
                                . 'from RiskBundle:Slot s '
                                . 'inner join RiskBundle:Box b with s.box=b.id '
                                . 'inner join RiskBundle:Player p with b.player=p.id '
                                . 'where p.id = :idp '
                                . 'and s.free=false '
                                . 'order by b.id ASC'
                        )
                        ->setParameter('idp', $idPlayer)
                        ->getResult();
    }

}
